apiVersion: v1
kind: Service
metadata:
  name: phoros-svc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "phoros.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
  selector:
    {{- include "phoros.selectorLabels" . | nindent 4 }}
