{{- if .Values.ingress.enabled -}}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: traefik
spec:
  replicas: {{ .Values.ingress.replicas }}
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v3.1
          args:
            - --providers.kubernetescrd
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --providers.kubernetesingress.namespaces={{ .Values.namespace }}

          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.ingress.type }}
  ports:
    - name: web
      targetPort: 80
      port: 80
  selector:
    app: traefik

---
{{- end -}}